# Generated by Django 4.0.4 on 2023-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='password',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
