# Generated by Django 4.0.4 on 2023-05-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0002_mechanic_password'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_types', to='mechanic.mechanic'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
